"""
Unit tests for the transpiler core.
"""

import pytest

from forge.transpiler.core import Transpiler, TranspilerConfig, TranspileResult
from forge.transpiler.language import Language
from forge.llm.llm_config import LLMConfig


class TestTranspilerConfig:
    """Tests for TranspilerConfig."""

    def test_valid_config(self):
        """Test creating a valid config."""
        config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
        )
        assert config.source_language == Language.TYPESCRIPT
        assert config.target_language == Language.PYTHON
        assert config.use_llm is False
        assert config.preserve_comments is True

    def test_same_language_raises(self):
        """Test that same source and target raises error."""
        with pytest.raises(ValueError):
            TranspilerConfig(
                source_language=Language.PYTHON,
                target_language=Language.PYTHON,
            )

    def test_llm_config(self):
        """Test config with LLM settings."""
        llm_config = LLMConfig(model="gpt-4")
        config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            use_llm=True,
            llm_config=llm_config,
        )
        assert config.use_llm is True
        assert config.llm_config is not None
        assert config.llm_config.model == "gpt-4"


class TestTranspiler:
    """Tests for Transpiler class."""

    def setup_method(self):
        """Set up test fixtures."""
        self.config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            use_llm=False,
        )

    def test_create_transpiler(self):
        """Test creating a transpiler."""
        transpiler = Transpiler(self.config)
        assert transpiler.config == self.config

    def test_transpile_empty_string(self):
        """Test transpiling empty string."""
        transpiler = Transpiler(self.config)
        result = transpiler.transpile("")
        assert result.success is True
        assert result.output == ""

    def test_transpile_simple_code(self):
        """Test transpiling simple code."""
        transpiler = Transpiler(self.config)
        source = "const x: number = 42;"
        result = transpiler.transpile(source)
        assert result.success is True
        assert len(result.output) > 0

    def test_transpile_adds_header(self):
        """Test that header is added by default."""
        transpiler = Transpiler(self.config)
        source = "const x = 42;"
        result = transpiler.transpile(source)
        assert "Generated by Forge" in result.output
        assert "TypeScript" in result.output
        assert "Python" in result.output

    def test_transpile_without_header(self):
        """Test transpiling without header."""
        config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            add_header=False,
        )
        transpiler = Transpiler(config)
        source = "const x = 42;"
        result = transpiler.transpile(source)
        assert "Generated by Forge" not in result.output

    def test_transpile_metrics(self):
        """Test that metrics are calculated."""
        transpiler = Transpiler(self.config)
        source = "const x = 42;"
        result = transpiler.transpile(source)
        assert "elapsed_seconds" in result.metrics
        assert "source_lines" in result.metrics
        assert "output_lines" in result.metrics

    def test_transpile_ast_available(self):
        """Test that AST is available in result."""
        transpiler = Transpiler(self.config)
        source = "const x = 42;"
        result = transpiler.transpile(source)
        assert result.ast is not None

    def test_transpile_python_to_typescript(self):
        """Test transpiling Python to TypeScript."""
        config = TranspilerConfig(
            source_language=Language.PYTHON,
            target_language=Language.TYPESCRIPT,
        )
        transpiler = Transpiler(config)
        source = "x: int = 42"
        result = transpiler.transpile(source)
        assert result.success is True

    def test_transpile_typescript_to_rust(self):
        """Test transpiling TypeScript to Rust."""
        config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.RUST,
        )
        transpiler = Transpiler(config)
        source = "const x: number = 42;"
        result = transpiler.transpile(source)
        assert result.success is True

    def test_transpile_typescript_to_go(self):
        """Test transpiling TypeScript to Go."""
        config = TranspilerConfig(
            source_language=Language.TYPESCRIPT,
            target_language=Language.GO,
        )
        transpiler = Transpiler(config)
        source = "const x: number = 42;"
        result = transpiler.transpile(source)
        assert result.success is True


class TestTranspileResult:
    """Tests for TranspileResult dataclass."""

    def test_success_result(self):
        """Test creating a successful result."""
        result = TranspileResult(
            success=True,
            output="print('hello')",
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
        )
        assert result.has_errors is False
        assert result.has_warnings is False

    def test_result_with_errors(self):
        """Test result with errors."""
        result = TranspileResult(
            success=False,
            output="",
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            errors=["Parse error"],
        )
        assert result.has_errors is True
        assert result.has_warnings is False

    def test_result_with_warnings(self):
        """Test result with warnings."""
        result = TranspileResult(
            success=True,
            output="code",
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            warnings=["Warning message"],
        )
        assert result.has_errors is False
        assert result.has_warnings is True

    def test_str_representation(self):
        """Test string representation."""
        result = TranspileResult(
            success=True,
            output="code",
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
        )
        s = str(result)
        assert "Success" in s
        assert "TypeScript" in s
        assert "Python" in s

    def test_str_representation_with_errors(self):
        """Test string representation with errors."""
        result = TranspileResult(
            success=False,
            output="",
            source_language=Language.TYPESCRIPT,
            target_language=Language.PYTHON,
            errors=["Test error"],
        )
        s = str(result)
        assert "Failed" in s
        assert "Test error" in s
